const styledVariable = {
  LOGIN_INPUT_WIDTH: '460px;',
  LOGIN_INPUT_MIN_WIDTH: '460px;',
  LOGIN_INPUT_HEIGHT: '63px;',
  LOGIN_INPUT_MIN_HEIGHT: '63px;',

  SNS_LOGIN_BUTTON_WIDTH: '460px;',
  SNS_LOGIN_BUTTON_MIN_WIDTH: '460px;',
  SNS_LOGIN_BUTTON_HEIGHT: '63px;',
  SNS_LOGIN_BUTTON_MIN_HEIGHT: '63px;',

  LOGIN_BUTTON_BG_COLOR: '#c4c4c4;',
  GOOGLE_LOGIN_BUTTON_BG_COLOR: '#ee5050;',
  NAVER_LOGIN_BUTTON_BG_COLOR: '#68e865;',
  KAKAO_LOGIN_BUTTON_BG_COLOR: '#f8e434;'
};

export default styledVariable;
