name: Auto Deployment to S3 bucket

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-deploy:
    name:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: node_modules caching
        uses: actions/cache@v2
        with:
          path: ./aa-frontend/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: install dependency
        run: npm install
        working-directory: ./aa-frontend

      - name: create env file
        run: |
          touch .env.production
          echo REACT_APP_ENDPOINT=${{ secrets.REACT_APP_ENDPOINT }} >> .env.production
          echo REACT_APP_NAVER_MAP_ID=${{ secrets.REACT_APP_NAVER_MAP_ID }} >> .env.production
          cat .env.production
        working-directory: ./aa-frontend

      - name: build project
        run: npm run build:production
        working-directory: ./aa-frontend
        env:
          CI: false

      - name: Deploy S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            ./aa-frontend/build s3://www.awesomeanimals.net
